version: "2"
services:
  discovery:
    image: lxd/discovery
    ports:
     - "8761:8761"
  config-server-ms:
    image: lxd/config-server-ms
    ports:
     - "8888:8888"
    links:
     - discovery
  api-gateway-ms:
    image: lxd/api-gateway-ms
    ports:
     - "10000:10000"
    links:
     - discovery
     - config-server-ms
     - hello-ms
     - data-ms
     - tsi-ms
     - fem-ms
  hello-ms:
    image: lxd/hello-ms
    ports:
     - "9001:9001"
    links:
     - discovery
     - config-server-ms
  data-ms:
    image: lxd/data-ms
    ports:
     - "9002:9002"
    links:
     - discovery
     - config-server-ms
  tsi-ms:
    image: lxd/tsi-ms
    ports:
     - "9003:9003"
    links:
     - discovery
     - config-server-ms
  fem-ms:
    image: lxd/fem-ms
    ports:
     - "9004:9004"
    links:
     - discovery
     - config-server-ms