spring:
  profiles:
    active: dev

server:
  port: 10000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: api-gateway-ms
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
zuul:
  routes:
    hello:
      path: /hello/**
      serviceId: hello-ms
    data:
      path: /data/**
      serviceId: data-ms
    tsi:
      path: /tsi/**
      serviceId: tsi-ms
    fem:
      path: /fem/**
      serviceId: fem-ms
