server:
  port: 8888

eureka:
  instance:
    hostname: config-server-ms
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${HOME}/LXD/work/config-repo